#!/usr/bin/env bash

set -exuo pipefail
cd $(dirname $0)/..

source _script/go_version

function binary_compilation {
	# mix of:
	#  traefik build
	#  http://blog.wrouesnel.com/articles/Totally%20static%20Go%20builds/
	#  https://www.osso.nl/blog/golang-statically-linked/
	#  https://github.com/kubernetes/kubernetes/pull/26028/files
	# see also https://gcc.gnu.org/onlinedocs/gcc/Link-Options.html
	CGO_ENABLED=0 GOOS=linux go build -o out/tcpgoon \
		    -ldflags "-X 'main.buildstamp=$(date -u '+%Y-%m-%d_%I:%M:%S%p')' -X 'main.githash=${COMMIT_HASH}' -extldflags '-static'" -a -installsuffix nocgo -tags netgo
}

function docker_build {
	tag=$1
	execgroup="docker"
    sg $execgroup "docker build -t $tag ."
}

# main()
docker_name=${1:-"dachad/tcpgoon"}
go_version_check
binary_compilation
docker_build "${docker_name}"
