#!/usr/bin/env bash

set -exuo pipefail
cd $(dirname $0)/..

./_script/requirements
./_script/test
./_script/formatting_checks

if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" = "master" ]
then
    echo "INFO: Merging to master... time to build and deploy redistributables"
    docker_name="dachad/tcpgoon"
    ./_script/build "$docker_name"
    ./_script/deploy "$docker_name"
fi
