#!/usr/bin/env bash

cd $(dirname $0)/..
source _script/requirements
set -exuo pipefail

./_script/test
./_script/formatting_checks

TRAVIS_PULL_REQUEST=${TRAVIS_PULL_REQUEST:-""}
TRAVIS_BRANCH=${TRAVIS_BRANCH:-""}
dry_run=${1:-""}
if [ "$TRAVIS_PULL_REQUEST" == "false" ] && [ "$TRAVIS_BRANCH" = "master" ]
then
    echo "INFO: Merging to master... time to build and deploy redistributables"
    docker_image_name="dachad/tcpgoon"
    commit_hash=$(git rev-parse --short HEAD)
    run_as_group="docker"
    newgrp $run_as_group <<- END
		./_script/build "$docker_image_name" "$commit_hash"
		./_script/deploy "$docker_image_name" "$commit_hash" "$dry_run"
	END
fi
