#!/usr/bin/env bash

go_version_in_travis_yml=$(cat .travis.yml | grep "^go:" -A1 | grep "^- " | cut -d " " -f 2)

function go_version_check {
	go_version=$(go version  | cut -d " " -f 3)
	if $(test $? -ne 0)
	then
	    echo "INFO: go binary not available? go version failed"
	    return 1
	fi
	supported_go_version="go${go_version_in_travis_yml}"
	if $(test "$go_version" != "$supported_go_version")
	then
		echo "INFO: Unsupported go environment. You should use: $supported_go_version"
		return 1
	fi
}
