#!/usr/bin/env bash

set -exuo pipefail
cd $(dirname $0)/..

### COVERALLS INTEGRATION NOTES ###
# Initially looking official docs
# http://docs.coveralls.io/go
# But using this for multiple package support
# https://github.com/vitalyisaev2/ads/blob/master/.travis.yml

function coveralls_report() {
    echo "[*] Generating and uploading coveralls report"
    overalls -project=github.com/dachad/tcpgoon -covermode=count
    goveralls -coverprofile=overalls.coverprofile -service=travis-ci -repotoken $COVERALLS_TOKEN
}

function main_tests() {
    echo "[*] Running Tests"
    go test -v -cover -race ./...
}

# main()
main_tests
if [[ "$HOME" = "/home/travis" ]]
then
    coveralls_report
fi
