#!/usr/bin/env bash

set -euo pipefail
cd $(dirname $0)/../..

cd out/
PATH=".:$PATH"
cmdline1="tcpgoon --help"
cmdline2="tcpgoon run --help"

echo "% "${cmdline1}
eval "${cmdline1}"

echo "% "${cmdline2}
eval "${cmdline2}"
